spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  file:
    name: logs/smallbooks.log
  level:
    root: INFO
    com.silvio: DEBUG