server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: identity-service-public
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - name: JwtAuthFilter

        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/api/licenses/**
          filters:
            - name: JwtAuthFilter

        - id: elending-service
          uri: lb://elending-service
          predicates:
            - Path=/api/lending/**
          filters:
            - name: JwtAuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtAuthFilter

        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - name: JwtAuthFilter

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - name: JwtAuthFilter

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - name: JwtAuthFilter

        - id: ingestion-service
          uri: lb://ingestion-service
          predicates:
            - Path=/api/ingestion/**
          filters:
            - name: JwtAuthFilter

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/content/**
          filters:
            - name: JwtAuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: Duoc.1983Duoc.1983Duoc.1983Duoc.1983