server:
  port: 8088

spring:
  application:
    name: notification-service
  rabbitmq:
    listener:
      simple:
        observation-enabled: true   # Restaura traceId/spanId al consumir mensajes
  datasource:
    url: jdbc:mysql://localhost:3306/db_notifications?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/