spring:
  main:
    web-application-type: reactive
  application:
    name: msvc-gateway
  config:
    import: 'optional:configserver:http://config:8888'

logging:
  pattern:
    level: "%5p [%mdc{traceId:-NONE} %mdc{spanId:-NONE}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans